### ISSUE TITLE
ヘッダーを追加する

### ISSUE THREAD

**Issue by SatooRu65536** [SystemEngineeringTeam/project-exercises-kuso#6]
## ブランチ名
`issues/6-feat-header`

## イメージ
![ヘッダー](https://github.com/user-attachments/assets/145be24b-3ed8-41af-affa-c41ba5fdac84)

- 今のページのボタンに下線が出る機能の実装は後回しにする

## ファイル
```
src/components/Header/index.tsx
src/components/Header/index.module.scss
```

## ヘッダーの呼び出し
`src/app/(use-header)/layout.tsx` の `<header>へっだー(仮)</header>` をHeaderコンポーネントで置き換える

**Comment by ogasa897** [comment]
カーソルが各ボタンの上に乗った時はどうしますか？
